
const MyOrders = [

    {
        id: 1,
        date: "28/12/2019",
        daytime: "Monday 12:51",
        price: 1047,
        currency: "$",
        delivery: true,
        complete: false,
        cancel: false,
        return: false,
        image: require("../../assets/image/women/women_1.png"),
        images: [
            {path: require("../../assets/image/women/women_1.png")}
        ],
        count: 1,
        title: "Cotton Sweater Beige(Size: 40 - Color: Orange)",
        address: "Iris Watson\nP.O. Box 283 8562 Fusce Rd.\nFrederick Nebraska 20620\n(372) 587-2335",
        creditCard: "54** **** **** **45",
        paymentInformation: "(Payment Completed)",
        productInfo: "In Delivery",
        orderNo: 111158271,
        subTotal: 1032,
        shipment: 15,
        total: 1047,
        dealer: "mowega",
        cargoFirm: "mowega",
        cargoFirmLogo: require("../../assets/logo/logo_horizontal.png"),
        cargoTrackingNo: "555 4987 5565 1510",
        cargo: [
            {
                id: 1,
                situation: "Transfer Process",
                location: "Chicago/Transfer Center",
                date: "25/12/2019",
                isHere: false
            },
            {
                id: 2,
                situation: "Transfer Process",
                location: "New York/Transfer Center",
                date: "26/12/2019",
                isHere: true
            },
            {
                id: 3,
                situation: "Transfer Process",
                location: "New York/City Center ",
                date: "",
                isHere: false
            },
            {
                id: 4,
                situation: "Product shipped",
                location: "Your Address",
                date: "",
                isHere: false
            }
        ]
    },
    {
        id: 2,
        date: "21/12/2019",
        daytime: "Friday 17:38",
        price: 1047,
        currency: "$",
        delivery: false,
        complete: true,
        cancel: false,
        return: false,
        image: require("../../assets/image/women/women_2.png"),
        images: [
            {path: require("../../assets/image/women/women_2.png")},
            {path: require("../../assets/image/women/women_3.png")},
            {path: require("../../assets/image/women/women_4.png")}
        ],
        count: 3,
        title: "Cotton Sweater Beige(Size: 40 - Color: Orange)",
        address: "Iris Watson\nP.O. Box 283 8562 Fusce Rd.\nFrederick Nebraska 20620\n(372) 587-2335",
        creditCard: "54** **** **** **45",
        paymentInformation: "(Payment Completed)",
        productInfo: "Delivered",
        orderNo: 111158271,
        subTotal: 1032,
        shipment: 15,
        dealer: "mowega",
        cargoFirm: "mowega",
        cargoFirmLogo: require("../../assets/logo/logo_horizontal.png"),
        cargoTrackingNo: "555 4987 5565 1510",
        cargo: [
            {
                id: 1,
                situation: "Transfer Process",
                location: "Chicago/Transfer Center",
                date: "25/12/2019",
                isHere: false
            },
            {
                id: 2,
                situation: "Transfer Process",
                location: "New York/Transfer Center",
                date: "26/12/2019",
                isHere: false
            },
            {
                id: 3,
                situation: "Transfer Process",
                location: "New York/City Center ",
                date: "26/12/2019",
                isHere: false
            },
            {
                id: 4,
                situation: "Product shipped",
                location: "Your Address",
                date: "28/12/2019",
                isHere: true
            }
        ]
    },
    {
        id: 3,
        date: "28/11/2019",
        daytime: "Monday 12:51",
        price: 1047,
        currency: "$",
        delivery: true,
        complete: false,
        cancel: false,
        return: false,
        image: require("../../assets/image/women/women_3.png"),
        images: [
            {path: require("../../assets/image/women/women_3.png")}
        ],
        count: 1,
        title: "Cotton Sweater Beige(Size: 40 - Color: Orange)",
        address: "Iris Watson\nP.O. Box 283 8562 Fusce Rd.\nFrederick Nebraska 20620\n(372) 587-2335",
        creditCard: "54** **** **** **45",
        paymentInformation: "(Payment Completed)",
        productInfo: "In Delivery",
        orderNo: 111158271,
        subTotal: 1032,
        shipment: 15,
        dealer: "mowega",
        cargoFirm: "mowega",
        cargoFirmLogo: require("../../assets/logo/logo_horizontal.png"),
        cargoTrackingNo: "555 4987 5565 1510",
    },
    {
        id: 4,
        date: "28/11/2019",
        daytime: "Monday 12:51",
        price: 1047,
        currency: "$",
        delivery: false,
        complete: true,
        cancel: false,
        return: false,
        image: require("../../assets/image/women/women_4.png"),
        images: [
            {path: require("../../assets/image/women/women_4.png")}
        ],
        count: 1,
        title: "Cotton Sweater Beige(Size: 40 - Color: Orange)",
        address: "Iris Watson\nP.O. Box 283 8562 Fusce Rd.\nFrederick Nebraska 20620\n(372) 587-2335",
        creditCard: "54** **** **** **45",
        paymentInformation: "(Payment Completed)",
        productInfo: "Delivered",
        dealer: "mowega",
        cargoFirm: "mowega",
        cargoFirmLogo: require("../../assets/logo/logo_horizontal.png"),
        cargoTrackingNo: "555 4987 5565 1510",
        cargo: [
            {
                id: 1,
                situation: "Transfer Process",
                location: "Chicago/Transfer Center",
                date: "25/12/2019",
                isHere: false
            },
            {
                id: 2,
                situation: "Transfer Process",
                location: "New York/Transfer Center",
                date: "26/12/2019",
                isHere: false
            },
            {
                id: 3,
                situation: "Transfer Process",
                location: "New York/City Center ",
                date: "26/12/2019",
                isHere: false
            },
            {
                id: 4,
                situation: "Product shipped",
                location: "Your Address",
                date: "28/12/2019",
                isHere: true
            }
        ]
    },
    {
        id: 5,
        date: "28/10/2019",
        daytime: "Monday 12:51",
        price: 1047,
        currency: "$",
        delivery: true,
        complete: false,
        cancel: false,
        return: false,
        image: require("../../assets/image/women/women_5.png"),
        images: [
            {path: require("../../assets/image/women/women_5.png")},
            {path: require("../../assets/image/women/women_6.png")},
            {path: require("../../assets/image/women/women_1.png")},
            {path: require("../../assets/image/women/women_2.png")},
            {path: require("../../assets/image/women/women_3.png")},
        ],
        count: 5,
        title: "Cotton Sweater Beige(Size: 40 - Color: Orange)",
        address: "Iris Watson\nP.O. Box 283 8562 Fusce Rd.\nFrederick Nebraska 20620\n(372) 587-2335",
        creditCard: "54** **** **** **45",
        paymentInformation: "(Payment Completed)",
        productInfo: "In Delivery",
        orderNo: 111158271,
        subTotal: 1032,
        shipment: 15,
        dealer: "mowega",
        cargoFirm: "mowega",
        cargoFirmLogo: require("../../assets/logo/logo_horizontal.png"),
        cargoTrackingNo: "555 4987 5565 1510",
        cargo: [
            {
                id: 1,
                situation: "Transfer Process",
                location: "Chicago/Transfer Center",
                date: "25/12/2019",
                isHere: false
            },
            {
                id: 2,
                situation: "Transfer Process",
                location: "New York/Transfer Center",
                date: "26/12/2019",
                isHere: true
            },
            {
                id: 3,
                situation: "Transfer Process",
                location: "New York/City Center ",
                date: "",
                isHere: false
            },
            {
                id: 4,
                situation: "Product shipped",
                location: "Your Address",
                date: "",
                isHere: false
            }
        ]
    },
    {
        id: 6,
        date: "28/10/2019",
        daytime: "Monday 12:51",
        price: 2048,
        currency: "$",
        delivery: false,
        complete: true,
        cancel: false,
        return: false,
        image: require("../../assets/image/women/women_6.png"),
        images: [
            {path: require("../../assets/image/women/women_6.png")},
            {path: require("../../assets/image/women/women_1.png")}
        ],
        count: 2,
        title: "Cotton Sweater Beige(Size: 40 - Color: Orange)",
        address: "Iris Watson\nP.O. Box 283 8562 Fusce Rd.\nFrederick Nebraska 20620\n(372) 587-2335",
        creditCard: "54** **** **** **45",
        paymentInformation: "(Payment Completed)",
        productInfo: "Delivered",
        orderNo: 111158271,
        subTotal: 2033,
        shipment: 15,
        dealer: "mowega",
        cargoFirm: "mowega",
        cargoFirmLogo: require("../../assets/logo/logo_horizontal.png"),
        cargoTrackingNo: "555 4987 5565 1510",
        cargo: [
            {
                id: 1,
                situation: "Transfer Process",
                location: "Chicago/Transfer Center",
                date: "25/12/2019",
                isHere: false
            },
            {
                id: 2,
                situation: "Transfer Process",
                location: "New York/Transfer Center",
                date: "26/12/2019",
                isHere: false
            },
            {
                id: 3,
                situation: "Transfer Process",
                location: "New York/City Center ",
                date: "26/12/2019",
                isHere: false
            },
            {
                id: 4,
                situation: "Product shipped",
                location: "Your Address",
                date: "28/12/2019",
                isHere: true
            }
        ]
    },
    {
        id: 7,
        date: "28/12/2019",
        daytime: "Monday 12:51",
        price: 1047,
        currency: "$",
        delivery: false,
        complete: false,
        cancel: true,
        return: false,
        image: require("../../assets/image/women/women_1.png"),
        images: [
            {path: require("../../assets/image/women/women_1.png")}
        ],
        count: 1,
        title: "Cotton Sweater Beige(Size: 40 - Color: Orange)",
        address: "Iris Watson\nP.O. Box 283 8562 Fusce Rd.\nFrederick Nebraska 20620\n(372) 587-2335",
        creditCard: "54** **** **** **45",
        paymentInformation: "(Payment Completed)",
        productInfo: "Order canceled",
        reasonText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        cargo: [],
        orderNo: 111158271,
        subTotal: 1032,
        shipment: 15,
        dealer: "mowega",
        cargoFirm: "mowega",
        cargoFirmLogo: require("../../assets/logo/logo_horizontal.png"),
        cargoTrackingNo: "555 4987 5565 1510",
    },
    {
        id: 8,
        date: "28/12/2019",
        daytime: "Monday 12:51",
        price: 1047,
        currency: "$",
        delivery: false,
        complete: false,
        cancel: false,
        return: true,
        image: require("../../assets/image/women/women_1.png"),
        images: [
            {path: require("../../assets/image/women/women_1.png")},
            {path: require("../../assets/image/women/women_2.png")},
            {path: require("../../assets/image/women/women_3.png")},
            {path: require("../../assets/image/women/women_4.png")},
            {path: require("../../assets/image/women/women_5.png")},
        ],
        count: 5,
        title: "Cotton Sweater Beige(Size: 40 - Color: Orange)",
        address: "Iris Watson\nP.O. Box 283 8562 Fusce Rd.\nFrederick Nebraska 20620\n(372) 587-2335",
        creditCard: "54** **** **** **45",
        paymentInformation: "(Payment Completed)",
        productInfo: "Order returned",
        reasonText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        cargo: [],
        orderNo: 111158271,
        subTotal: 1032,
        shipment: 15,
        dealer: "mowega",
        cargoFirm: "mowega",
        cargoFirmLogo: require("../../assets/logo/logo_horizontal.png"),
        cargoTrackingNo: "555 4987 5565 1510",
    },
    {
        id: 9,
        date: "28/12/2019",
        daytime: "Monday 12:51",
        price: 1047,
        currency: "$",
        delivery: false,
        complete: false,
        cancel: false,
        return: true,
        image: require("../../assets/image/women/women_1.png"),
        images: [
            {path: require("../../assets/image/women/women_1.png")},
        ],
        count: 1,
        title: "Cotton Sweater Beige(Size: 40 - Color: Orange)",
        address: "Iris Watson\nP.O. Box 283 8562 Fusce Rd.\nFrederick Nebraska 20620\n(372) 587-2335",
        creditCard: "54** **** **** **45",
        paymentInformation: "(Payment Completed)",
        productInfo: "Order returned",
        reasonText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        cargo: [],
        orderNo: 111158271,
        subTotal: 1032,
        shipment: 15,
        dealer: "mowega",
        cargoFirm: "mowega",
        cargoFirmLogo: require("../../assets/logo/logo_horizontal.png"),
        cargoTrackingNo: "555 4987 5565 1510",
    },
    {
        id: 10,
        date: "28/12/2019",
        daytime: "Monday 12:51",
        price: 1047,
        currency: "$",
        delivery: false,
        complete: false,
        cancel: true,
        return: false,
        image: require("../../assets/image/women/women_1.png"),
        images: [
            {path: require("../../assets/image/women/women_1.png")},
            {path: require("../../assets/image/women/women_2.png")},
            {path: require("../../assets/image/women/women_3.png")}
        ],
        count: 3,
        title: "Cotton Sweater Beige(Size: 40 - Color: Orange)",
        address: "Iris Watson\nP.O. Box 283 8562 Fusce Rd.\nFrederick Nebraska 20620\n(372) 587-2335",
        creditCard: "54** **** **** **45",
        paymentInformation: "(Payment Completed)",
        productInfo: "Order canceled",
        reasonText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        cargo: [],
        orderNo: 111158271,
        subTotal: 1032,
        shipment: 15,
        dealer: "mowega",
        cargoFirm: "mowega",
        cargoFirmLogo: require("../../assets/logo/logo_horizontal.png"),
        cargoTrackingNo: "555 4987 5565 1510",
    },

];

export default MyOrders;
